import type { GameCatalogEntry } from "../core/gameCatalog"

export const gameManifest: GameCatalogEntry[] = [
  {
    id: "tic-tac-toe",
    name: "Tic Tac Toe",
    icon: "grid",
    backgroundColor: "#FF5252",
    description: "Challenge a friend or the bot to the classic three-in-a-row duel.",
    instructions: "Tap to place your mark. Get three in a row to win!",
    status: "playable",
    componentId: "tic-tac-toe",
    difficulty: 1,
    minPlayers: 1,
    maxPlayers: 2,
    category: "board",
    supportedModes: ["local", "bot"],
  },
  {
    id: "air-hockey",
    name: "Air Hockey",
    icon: "disc",
    backgroundColor: "#2196F3",
    description: "Slide fast, score goals, and protect your side of the arena.",
    instructions: "Drag your paddle to hit the puck. Score by getting the puck in your opponent's goal!",
    status: "playable",
    componentId: "air-hockey",
    difficulty: 2,
    minPlayers: 1,
    maxPlayers: 2,
    category: "sports",
    supportedModes: ["local", "bot"],
  },
  {
    id: "ping-pong",
    name: "Ping Pong",
    icon: "table-tennis",
    backgroundColor: "#FFC107",
    description: "Keep the rally alive with quick reflexes and spin control.",
    instructions: "Swipe to move your paddle. Don't let the ball pass you!",
    status: "playable",
    componentId: "ping-pong",
    difficulty: 2,
    minPlayers: 1,
    maxPlayers: 2,
    category: "sports",
    supportedModes: ["local", "bot"],
  },
  {
    id: "spinner-war",
    name: "Spinner War",
    icon: "refresh-circle",
    backgroundColor: "#607D8B",
    description: "Spin up, collide, and launch your rival out of the arena.",
    instructions: "Tap and hold to spin. Push your opponent off the platform to win!",
    status: "playable",
    componentId: "spinner-war",
    difficulty: 3,
    minPlayers: 1,
    maxPlayers: 2,
    category: "action",
    supportedModes: ["local", "bot"],
  },
  {
    id: "connect-four",
    name: "Connect Four",
    icon: "apps",
    backgroundColor: "#E91E63",
    description: "Drop discs and string four together before your opponent does.",
    instructions: "Tap a column to drop your disc. Connect four discs vertically, horizontally, or diagonally to win!",
    status: "coming-soon",
    difficulty: 2,
    minPlayers: 1,
    maxPlayers: 2,
    category: "board",
    isNew: true,
    supportedModes: ["local", "bot"],
  },
  {
    id: "dots-and-boxes",
    name: "Dots & Boxes",
    icon: "square",
    backgroundColor: "#3F51B5",
    description: "Draw the final line to steal the square and extend your turn.",
    instructions: "Tap between dots to draw a line. Complete a box to earn a point and go again!",
    status: "coming-soon",
    difficulty: 2,
    minPlayers: 1,
    maxPlayers: 2,
    category: "board",
    supportedModes: ["local", "bot"],
  },
  {
    id: "chess",
    name: "Chess",
    icon: "options",
    backgroundColor: "#009688",
    description: "Strategise every move in the timeless duel of kings and queens.",
    instructions: "Tap to select a piece, then tap to move. Checkmate your opponent's king to win!",
    status: "coming-soon",
    difficulty: 4,
    minPlayers: 1,
    maxPlayers: 2,
    category: "board",
    isPremium: true,
    supportedModes: ["local", "bot"],
  },
  {
    id: "mini-golf",
    name: "Mini Golf",
    icon: "golf",
    backgroundColor: "#8BC34A",
    description: "Putt through whimsical courses and master the tricky bank shots.",
    instructions: "Drag to aim and set power. Get the ball in the hole with fewer strokes than your opponent!",
    status: "coming-soon",
    difficulty: 3,
    minPlayers: 1,
    maxPlayers: 4,
    category: "sports",
    isPremium: true,
    supportedModes: ["local"],
  },
]
