import type { SoundPlaybackKey } from "../contexts/SoundContext"

export const soundManifest: Record<SoundPlaybackKey, any> = {
  "background-music": require("../assets/sounds/background-music.mp3"),
  "button-press": require("../assets/sounds/button-press.mp3"),
  "game-start": require("../assets/sounds/game-start.mp3"),
  win: require("../assets/sounds/win.mp3"),
  draw: require("../assets/sounds/draw.mp3"),
  "cell-tap": require("../assets/sounds/cell-tap.mp3"),
  "invalid-move": require("../assets/sounds/invalid-move.mp3"),
  toggle: require("../assets/sounds/toggle.mp3"),
  "wall-hit": require("../assets/sounds/wall-hit.mp3"),
  "paddle-hit": require("../assets/sounds/paddle-hit.mp3"),
  score: require("../assets/sounds/score.mp3"),
  // Optional alternates used by Air Hockey goal FX if present
  // Fallback to primary if alternates not found at runtime
  // These keys are still valid SoundPlaybackKey via require calls
  collision: require("../assets/sounds/collision.mp3"),
  "round-start": require("../assets/sounds/round-start.mp3"),
  "eat-food": require("../assets/sounds/eat-food.mp3"),
}

export const imageManifest: number[] = [
  require("../assets/images/logo.png"),
  require("../assets/images/background.png"),
  require("../assets/images/ping-pong-bg.png"),
  require("../assets/images/air-hockey-bg.png"),
  require("../assets/images/tic-tac-toe-bg.png"),
  require("../assets/images/spinner-war-bg.png"),
  require("../assets/images/settings-bg.png"),
  require("../assets/images/snakes-duel/winter-head.png"),
  require("../assets/images/snakes-duel/winter-body.png"),
  require("../assets/images/snakes-duel/winter-turn.png"),
  require("../assets/images/snakes-duel/winter-tail.png"),
  require("../assets/images/snakes-duel/spring-head.png"),
  require("../assets/images/snakes-duel/spring-body.png"),
  require("../assets/images/snakes-duel/spring-turn.png"),
  require("../assets/images/snakes-duel/spring-tail.png"),
  require("../assets/images/snakes-duel/summer-head.png"),
  require("../assets/images/snakes-duel/summer-body.png"),
  require("../assets/images/snakes-duel/summer-turn.png"),
  require("../assets/images/snakes-duel/summer-tail.png"),
  require("../assets/images/snakes-duel/autumn-head.png"),
  require("../assets/images/snakes-duel/autumn-body.png"),
  require("../assets/images/snakes-duel/autumn-turn.png"),
  require("../assets/images/snakes-duel/autumn-tail.png"),
  require("../assets/particles/winter-particle.png"),
  require("../assets/particles/spring-particle.png"),
  require("../assets/particles/summer-particle.png"),
  require("../assets/particles/autumn-particle.png"),
  require("../assets/images/ui/panel-1600x320.png"),
  require("../assets/images/ui/panel-1200x400.png"),
  require("../assets/images/ui/icon-back-256.png"),
  require("../assets/images/ui/icon-back-128.png"),
  require("../assets/images/ui/icon-play-256.png"),
  require("../assets/images/ui/icon-play-128.png"),
  require("../assets/images/ui/icon-settings-256.png"),
  require("../assets/images/ui/icon-settings-128.png"),
  require("../assets/images/ui/icon-star-256.png"),
  require("../assets/images/ui/icon-star-128.png"),
  require("../assets/images/ui/icon-trophy-256.png"),
  require("../assets/images/ui/icon-trophy-128.png"),
  require("../assets/images/home/hero-spring.png"),
  require("../assets/images/home/hero-summer.png"),
  require("../assets/images/home/hero-autumn.png"),
  require("../assets/images/home/hero-winter.png"),
  require("../assets/images/home/categories/board.png"),
  require("../assets/images/home/categories/puzzle.png"),
  require("../assets/images/home/categories/reflex.png"),
  require("../assets/images/home/categories/sports.png"),
  require("../assets/images/seasonal/banner-spring.png"),
  require("../assets/images/seasonal/banner-summer.png"),
  require("../assets/images/seasonal/banner-autumn.png"),
  require("../assets/images/seasonal/banner-winter.png"),
  require("../assets/images/air-hockey/arena.png"),
  require("../assets/images/tic-tac-toe/board-premium.png"),
  require("../assets/images/ping-pong/table-spring.png"),
  require("../assets/images/ping-pong/table-summer.png"),
  require("../assets/images/ping-pong/table-autumn.png"),
  require("../assets/images/ping-pong/table-winter.png"),
  require("../assets/images/ping-pong/crowd-layer-near.png"),
  require("../assets/images/ping-pong/crowd-layer-far.png"),
  require("../assets/images/spinner-war/arena-1.png"),
  require("../assets/images/spinner-war/arena-2.png"),
  require("../assets/images/spinner-war/arena-3.png"),
  require("../assets/images/spinner-war/overlay-vignette.png"),
  require("../assets/images/spinner-war/boost-1.png"),
  require("../assets/images/spinner-war/boost-2.png"),
  require("../assets/images/spinner-war/boost-3.png"),
  require("../assets/images/spinner-war/boost-4.png"),
  require("../assets/images/snakes-duel/grid-spring.png"),
  require("../assets/images/snakes-duel/grid-summer.png"),
  require("../assets/images/snakes-duel/grid-autumn.png"),
  require("../assets/images/snakes-duel/grid-winter.png"),
  require("../assets/images/snakes-duel/apple-spring.png"),
  require("../assets/images/snakes-duel/apple-summer.png"),
  require("../assets/images/snakes-duel/apple-autumn.png"),
  require("../assets/images/snakes-duel/apple-winter.png"),
  require("../assets/images/penalty-kicks/stadium-1.png"),
  require("../assets/images/penalty-kicks/stadium-2.png"),
  require("../assets/images/penalty-kicks/stadium-3.png"),
  require("../assets/images/penalty-kicks/net-overlay.png"),
  require("../assets/images/penalty-kicks/characters/keeper-front.png"),
  require("../assets/images/penalty-kicks/characters/shooter-side.png"),
  require("../assets/particles/air-hockey/goal-light.png"),
  require("../assets/particles/air-hockey/puck-trail.png"),
  require("../assets/particles/air-hockey/sparks.png"),
  require("../assets/particles/ping-pong/paddle-trail.png"),
  require("../assets/particles/ping-pong/spin.png"),
  require("../assets/particles/spinner-war/impact-burst.png"),
  require("../assets/particles/tic-tac-toe/tictactoe-win.png"),
  require("../assets/particles/tic-tac-toe/tictactoe-confetti.png"),
  require("../assets/particles/penalty-kicks/ball-trail.png"),
  require("../assets/particles/penalty-kicks/confetti.png"),
  require("../assets/particles/snakes-duel/explosion.png"),
]
export const particleManifest = {
  "snakes-winter": require("../assets/particles/winter-particle.png"),
  "snakes-spring": require("../assets/particles/spring-particle.png"),
  "snakes-summer": require("../assets/particles/summer-particle.png"),
  "snakes-autumn": require("../assets/particles/autumn-particle.png"),
  "air-hockey-goal-light": require("../assets/particles/air-hockey/goal-light.png"),
  "air-hockey-puck-trail": require("../assets/particles/air-hockey/puck-trail.png"),
  "air-hockey-sparks": require("../assets/particles/air-hockey/sparks.png"),
  "ping-pong-paddle-trail": require("../assets/particles/ping-pong/paddle-trail.png"),
  "ping-pong-spin": require("../assets/particles/ping-pong/spin.png"),
  "spinner-war-impact": require("../assets/particles/spinner-war/impact-burst.png"),
  "tic-tac-toe-win": require("../assets/particles/tic-tac-toe/tictactoe-win.png"),
  "tic-tac-toe-confetti": require("../assets/particles/tic-tac-toe/tictactoe-confetti.png"),
  "penalty-kicks-ball-trail": require("../assets/particles/penalty-kicks/ball-trail.png"),
  "penalty-kicks-confetti": require("../assets/particles/penalty-kicks/confetti.png"),
  "snakes-explosion": require("../assets/particles/snakes-duel/explosion.png"),
}

